### ISSUE TITLE
[Suggestion] Swap the position of ORCID and institutional login buttons

### ISSUE THREAD

**Issue by kchatpar** [CONP-PCNO/conp-authentication#4]
On the login page for the CONP website. Consider, swapping the positions of the auto-sign in methods(ORCID and Institution). 

The reason is that, more people are associated with institutions relative to Orcid. For example, most undergraduate students don't have ORCID's but are interested in the data. Most people don't get ORCID's until the publish there first paper.

**Comment by jbpoline** [comment]
True, at the same time I would love students to get an orcid account, they will almost surely need one in the future, and while in academia we change institutions orcid stays, so if this could be a nice incentive

**Comment by driusan** [comment]
I don't have any strong feelings about this, but wouldn't they be able to associate an orcid to their accounts afterwards?

**Comment by paiva** [comment]
Institution login is now placed over ORCID to "prioritize" users that are whitelisted
